/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntregadoresRouteImport } from './routes/entregadores'
import { Route as EntregadorRouteImport } from './routes/entregador'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresRoute = EntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorRoute = EntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/entregador': typeof EntregadorRoute
  '/entregadores': typeof EntregadoresRoute
  '/login': typeof LoginRoute
  '/meus-pedidos': typeof MeusPedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/entregador': typeof EntregadorRoute
  '/entregadores': typeof EntregadoresRoute
  '/login': typeof LoginRoute
  '/meus-pedidos': typeof MeusPedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/entregador': typeof EntregadorRoute
  '/entregadores': typeof EntregadoresRoute
  '/login': typeof LoginRoute
  '/meus-pedidos': typeof MeusPedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/entregador'
    | '/entregadores'
    | '/login'
    | '/meus-pedidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/entregador'
    | '/entregadores'
    | '/login'
    | '/meus-pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/entregador'
    | '/entregadores'
    | '/login'
    | '/meus-pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  EntregadorRoute: typeof EntregadorRoute
  EntregadoresRoute: typeof EntregadoresRoute
  LoginRoute: typeof LoginRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores': {
      id: '/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof EntregadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador': {
      id: '/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof EntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  EntregadorRoute: EntregadorRoute,
  EntregadoresRoute: EntregadoresRoute,
  LoginRoute: LoginRoute,
  MeusPedidosRoute: MeusPedidosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
