// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmphvcfobqbpujdigrfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtcGh2Y2ZvYnFicHVqZGlncmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MjgzMzYsImV4cCI6MjA5NTQwNDMzNn0.wmy_pwCFXpQuscf65q1mTBMouu5dAlp2heFJ8oKRdXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});